/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.Socket;

/**
 *
 * @author Admin
 */
public class ChatClient extends javax.swing.JFrame {

    /**
     * Creates new form ChatClient
     */
    static Socket s;
    static DataInputStream in;
    static DataOutputStream out;
    
    public ChatClient() {
        initComponents();
        setLocationRelativeTo(this);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
//        addWindowListener(new WindowAdapter(){
//            @Override
//            public void windowClosing(WindowEvent e) {
//                ChatList chatList = new ChatList();
//                chatList.setVisible(true);
//                dispose();
//            }
//            
//        });
    }
    public void connectToServer(String address, int port) {
        new Thread(() -> {
            String inputtext = "";
            try {
                s = new Socket(address, port);
                in = new DataInputStream(s.getInputStream());
                out = new DataOutputStream(s.getOutputStream());
                while (!inputtext.equals("exit")) {
                    inputtext = in.readUTF();
                    String formattedMessage = String.format("%-10s\t%s", "Admin:", inputtext);
                    clientarea.setText(clientarea.getText().trim() + "\n" + formattedMessage);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            finally {
                try {
                    if (in != null) in.close();
                    if (out != null) out.close();
                    if (s != null) s.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }).start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        clientarea = new javax.swing.JTextArea();
        clienttxt = new javax.swing.JTextField();
        clientbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contact");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clientarea.setColumns(20);
        clientarea.setForeground(new java.awt.Color(51, 51, 51));
        clientarea.setRows(5);
        jScrollPane1.setViewportView(clientarea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 390, 220));

        clienttxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clienttxt.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(clienttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 310, 50));

        clientbtn.setText("Gửi");
        clientbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientbtnActionPerformed(evt);
            }
        });
        getContentPane().add(clientbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 50, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientbtnActionPerformed
        // TODO add your handling code here:
         String outputtext = clienttxt.getText().trim();
        try {
            if (!outputtext.isEmpty()) {
                String formattedMessage = String.format("%-10s\t%s", "You:", outputtext);
                clientarea.setText(clientarea.getText().trim() + "\n" + formattedMessage);
                out.writeUTF(outputtext);
                clienttxt.setText(""); 
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_clientbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatClient().setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextArea clientarea;
    private javax.swing.JButton clientbtn;
    private javax.swing.JTextField clienttxt;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
