    /*
    * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
    * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
    */
    package com.view;
    import java.sql.ResultSet;
    import javax.swing.JFrame;
    import javax.swing.JOptionPane;
    import java.sql.Connection;
    import java.sql.DriverManager;
    import java.sql.PreparedStatement;
    import java.awt.Color;



    /**
    *
    * @author Cong Huy
    */
    public class Login extends javax.swing.JFrame {

    /**
    * Creates new form login1
    */
    public Login() {
    initComponents();
    setLocationRelativeTo(null);
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gif = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        taikhoandangnhap = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jlable1 = new javax.swing.JLabel();
        matkhaudangnhap = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jlable2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1380, 600));
        setMinimumSize(new java.awt.Dimension(1210, 600));
        setPreferredSize(new java.awt.Dimension(1210, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Capture (2).png"))); // NOI18N
        jPanel1.add(gif, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        jPanel2.setBackground(new java.awt.Color(157, 192, 235));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("SF Mono", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Username or Email");
        jLabel6.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 300, 60));

        taikhoandangnhap.setBackground(new Color(0,0,0,0));
        taikhoandangnhap.setFont(new java.awt.Font("SF Mono", 1, 16)); // NOI18N
        taikhoandangnhap.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        taikhoandangnhap.setPreferredSize(new java.awt.Dimension(70, 30));
        taikhoandangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taikhoandangnhapActionPerformed(evt);
            }
        });
        jPanel2.add(taikhoandangnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 305, 33));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("SF Mono", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Password");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 290, -1));

        jButton6.setBackground(new java.awt.Color(250, 211, 238));
        jButton6.setFont(new java.awt.Font("SF Mono", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 51, 51));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8-login-50.png"))); // NOI18N
        jButton6.setText("Log In");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setPreferredSize(new java.awt.Dimension(81, 50));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 187, 60));

        jButton7.setBackground(new java.awt.Color(250, 211, 238));
        jButton7.setFont(new java.awt.Font("SF Mono", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(51, 51, 51));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8-sign-up-50.png"))); // NOI18N
        jButton7.setText("Sign Up");
        jButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setMaximumSize(new java.awt.Dimension(117, 33));
        jButton7.setMinimumSize(new java.awt.Dimension(117, 33));
        jButton7.setPreferredSize(new java.awt.Dimension(81, 50));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 187, 60));

        jlable1.setForeground(new java.awt.Color(255, 255, 255));
        jlable1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/visible.png"))); // NOI18N
        jlable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlable1MouseClicked(evt);
            }
        });
        jPanel2.add(jlable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 60, 60));

        matkhaudangnhap.setBackground(new Color(0,0,0,0));
        matkhaudangnhap.setFont(new java.awt.Font("SF Mono", 1, 16)); // NOI18N
        matkhaudangnhap.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel2.add(matkhaudangnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 305, 33));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/User_2.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 30, 120));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Lock_2.png"))); // NOI18N
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 70, 80));
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, 60, 40));

        jLabel4.setFont(new java.awt.Font("SF Mono", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Welcome to our application");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 550, 50));

        jLabel5.setBackground(java.awt.SystemColor.controlHighlight);
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 45)); // NOI18N
        jLabel5.setText("Manage Contacts");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 380, 70));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8-contacts-60.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8-contacts-60.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 150, -1));

        jlable2.setForeground(new java.awt.Color(255, 255, 255));
        jlable2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/invisible.png"))); // NOI18N
        jlable2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlable2MouseClicked(evt);
            }
        });
        jPanel2.add(jlable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 60, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 770, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taikhoandangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taikhoandangnhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taikhoandangnhapActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String Taikhoan, Matkhau, passDB;
        Taikhoan = taikhoandangnhap.getText();
        Matkhau = matkhaudangnhap.getText();
        String url, user, pass;
        url = "jdbc:mysql://localhost:3306/doancoso";
        user = "root";
        pass = "050813";
        if (Taikhoan.isEmpty()) {
            JOptionPane.showMessageDialog(new JFrame(), "PLEASE ENTER USERNAME", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (Matkhau.isEmpty()) {
            JOptionPane.showMessageDialog(new JFrame(), "PLEASE ENTER PASSWORD", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
         try(
            Connection con = DriverManager.getConnection(url, user, pass);
            PreparedStatement pst = con.prepareStatement("SELECT * FROM dangkitaikhoan WHERE taikhoan=? and matkhau=?");
                 ){
            pst.setString(1, Taikhoan);
            pst.setString(2, Matkhau);
        try(ResultSet rs = pst.executeQuery())
        {
            if (rs.next()) {
            JOptionPane.showMessageDialog(rootPane, "LOGIN SUCCESSFUL!");
            this.setVisible(false);
            Menu menu = new Menu();
            menu.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "INVALID USERNAME OR PASSWORD", "Error", JOptionPane.ERROR_MESSAGE);
            matkhaudangnhap.setText("");
        }
        }
        }
        catch (Exception e) {
        e.printStackTrace();
    } 
}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Signup signup = new Signup();
        signup.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jlable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlable1MouseClicked
        matkhaudangnhap.setEchoChar((char)0);
        jlable1.setVisible(false);
        jlable2.setVisible(true);
    }//GEN-LAST:event_jlable1MouseClicked

    private void jlable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlable2MouseClicked
        // TODO add your handling code here:
        matkhaudangnhap.setEchoChar('*');
        jlable1.setVisible(true);
        jlable2.setVisible(false);
    }//GEN-LAST:event_jlable2MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new Login().setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gif;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlable1;
    private javax.swing.JLabel jlable2;
    private javax.swing.JPasswordField matkhaudangnhap;
    private javax.swing.JTextField taikhoandangnhap;
    // End of variables declaration//GEN-END:variables
    }
