/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import java.sql.ResultSet;
/**
 *
 * @author Admin
 */
public class Signup extends javax.swing.JFrame {

    public Signup() {
        initComponents();
        setLocationRelativeTo(this);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                Login login = new Login();
                login.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        taikhoan = new javax.swing.JTextField();
        matkhau = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        xacnhanmatkhau = new javax.swing.JTextField();
        btnregister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 205));
        setPreferredSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(157, 192, 235));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8-sign-up-50.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("SF Mono", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Username or Email");
        jLabel6.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 220, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Add User Male.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, 40));

        taikhoan.setBackground(new Color(0,0,0,0));
        taikhoan.setFont(new java.awt.Font("SF Mono", 1, 18)); // NOI18N
        taikhoan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        taikhoan.setPreferredSize(new java.awt.Dimension(70, 30));
        taikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taikhoanActionPerformed(evt);
            }
        });
        jPanel1.add(taikhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 300, -1));

        matkhau.setBackground(new Color(0,0,0,0));
        matkhau.setFont(new java.awt.Font("SF Mono", 1, 18)); // NOI18N
        matkhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        matkhau.setPreferredSize(new java.awt.Dimension(70, 30));
        matkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matkhauActionPerformed(evt);
            }
        });
        jPanel1.add(matkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 300, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Password_1.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("SF Mono", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Password");
        jLabel8.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("SF Mono", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Confirm Password");
        jLabel7.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 200, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Lock Orientation.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        xacnhanmatkhau.setBackground(new Color(0,0,0,0));
        xacnhanmatkhau.setFont(new java.awt.Font("SF Mono", 1, 18)); // NOI18N
        xacnhanmatkhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        xacnhanmatkhau.setPreferredSize(new java.awt.Dimension(70, 30));
        xacnhanmatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xacnhanmatkhauActionPerformed(evt);
            }
        });
        jPanel1.add(xacnhanmatkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 300, -1));

        btnregister.setBackground(new java.awt.Color(250, 211, 238));
        btnregister.setFont(new java.awt.Font("SF Mono", 1, 14)); // NOI18N
        btnregister.setForeground(new java.awt.Color(51, 51, 51));
        btnregister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8-tick-50.png"))); // NOI18N
        btnregister.setText("Sign Up");
        btnregister.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnregister.setMaximumSize(new java.awt.Dimension(117, 33));
        btnregister.setMinimumSize(new java.awt.Dimension(117, 33));
        btnregister.setPreferredSize(new java.awt.Dimension(81, 50));
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 160, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 390, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taikhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taikhoanActionPerformed

    private void matkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matkhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matkhauActionPerformed

    private void xacnhanmatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xacnhanmatkhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xacnhanmatkhauActionPerformed

    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed
        String Taikhoan , Matkhau , Xacnhanmatkhau;
        Taikhoan = taikhoan.getText();
        Matkhau = matkhau.getText();
        Xacnhanmatkhau = xacnhanmatkhau.getText();
        String url , user , pass ;
        url = "jdbc:mysql://localhost:3306/doancoso";
        user = "root";
        pass = "050813";
            if (Taikhoan.isEmpty()) {
                JOptionPane.showMessageDialog(new JFrame(), "PLEASE ENTER USERNAME", "Error",JOptionPane.ERROR_MESSAGE);
            } else if (Matkhau.isEmpty()) {
                JOptionPane.showMessageDialog(new JFrame(), "PLEASE ENTER PASSWORD", "Error",JOptionPane.ERROR_MESSAGE);
            } else if (Xacnhanmatkhau.isEmpty()) {
                JOptionPane.showMessageDialog(new JFrame(), "PLEASE CONFIRM PASSWORD", "Error",JOptionPane.ERROR_MESSAGE);
            } else if (!Matkhau.equals(Xacnhanmatkhau)) {
                JOptionPane.showMessageDialog(new JFrame(), "PASSWORDS DO NOT MATCH", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                try (
                    Connection con = DriverManager.getConnection(url,user,pass);
                    PreparedStatement pst = con.prepareStatement("select taikhoan from dangkitaikhoan where `taikhoan` =?");
                    PreparedStatement st = con.prepareStatement("INSERT INTO dangkitaikhoan(`taikhoan`, `matkhau`, `xacnhanmatkhau`)  VALUES(?, ?, ?)");
                        ){
                    pst.setString(1, Taikhoan);
                    try(ResultSet rs = pst.executeQuery())
                    {
                        if ( rs.next()) {
                    JOptionPane.showMessageDialog(rootPane, "USERNAME ALREADY EXISTS", "Error", JOptionPane.ERROR_MESSAGE);
                }
                    else 
                    {
                        st.setString(1, Taikhoan);
                        st.setString(2, Matkhau);
                        st.setString(3, Xacnhanmatkhau);
                        st.executeUpdate();
                        showMessageDialog(null, "REGISTRATION SUCCESSFUL!");
                        Login login = new Login();
                        login.setVisible(true);
                        this.setVisible(false); 
                        this.dispose();
                        }
                        }
                } catch (Exception e) {
                    e.printStackTrace();
                } 
            }
    }//GEN-LAST:event_btnregisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregister;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField matkhau;
    private javax.swing.JTextField taikhoan;
    private javax.swing.JTextField xacnhanmatkhau;
    // End of variables declaration//GEN-END:variables
}
